modLoader="javafml"
loaderVersion="*"
license="${license}"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="gvoze32"
description='''${description}'''

[[dependencies.${id}]]
modId="forge"
mandatory=true
versionRange="*"
ordering="NONE"
side="BOTH"

[[dependencies.${id}]]
modId="minecraft"
mandatory=true
versionRange="[${minecraftVersion},)"
ordering="NONE"
side="BOTH"
