modLoader="javafml"
loaderVersion="*"
license="${license}"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
authors="gvoze32"
description='''${description}'''

[[dependencies.${id}]]
modId="minecraft"
type="required"
versionRange="[${minecraftVersion}]"
ordering="NONE"
side="BOTH"
